name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_ACCOUNT_ID : ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION : "eu-north-1"

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} #change to reflect your IAM role’s ARN
          role-session-name: docplanner-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build & Push Go image
      - name: Build and push Go image
        uses: docker/build-push-action@v6
        with:
          context: ./golang
          file: ./golang/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/doc-go:cache
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/doc-go:${{ github.sha }}
        #   cache-from: type=gha
        #   cache-to: type=gha,mode=max

      # Build & Push PHP image
      - name: Build and push PHP image
        uses: docker/build-push-action@v6
        with:
          context: ./php
          file: ./php/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/doc-php:cache
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/doc-php:${{ github.sha }}
        #   cache-from: type=gha
        #   cache-to: type=gha,mode=max